name: Dependency Update

on:
  workflow_dispatch:

jobs:
  update-deps:
    uses: Xemelgo/.github/.github/workflows/update-dependencies-with-codemod.yml@main
    with:
      package_name: ''
      branch_name: 'deps/consolidated-update-with-migrations'
      dry_run: false
      team_reviewers: 'Xemelgo/edge-ingestion-team'
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      XEMELGO_DOTGITHUB_READ_PAT: ${{ secrets.XEMELGO_DOTGITHUB_READ_PAT }}
